development:
  adapter: postgresql
  encoding: unicode
  database: instagator
  host: localhost
  username: instagator
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: instagator_test
  host: localhost
  pool: 5
  username: instagator
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: instagator_production
  pool: 25
  username: instagator
  password:
